
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/hfshen.github.io' #change it according to your repository name



# Profile information
yourname: Hongfan Shen  ## put your name
title: 'Brain Researcher &amp; Engineer'  ## your title
location: Seoul, Korea


## Social Profiles
facebook: https://www.facebook.com/hongfan.shen
linkedin: https://www.linkedin.com/in/hfshen/



# Update all the sections by editing the files inside _includes folder.

#theme: jekyll-theme-cayman
